// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Z9HtSAIQZpEOWKUbhJflNJW2yhP-5MI',
    appId: '1:1026894590428:web:520497aa8df5170b885f19',
    messagingSenderId: '1026894590428',
    projectId: 'prakppbfix',
    authDomain: 'prakppbfix.firebaseapp.com',
    storageBucket: 'prakppbfix.appspot.com',
    measurementId: 'G-VJDF0E1EV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADIaY8SZ1iZnRGNqWcucCPhIE23yXYo90',
    appId: '1:1026894590428:android:cc342585162ee6c7885f19',
    messagingSenderId: '1026894590428',
    projectId: 'prakppbfix',
    storageBucket: 'prakppbfix.appspot.com',
  );
}
